### ISSUE TITLE
Plugin Catalog: WASM plugins that are not Go code are not found from GitHub

### ISSUE THREAD

**Issue by mobileskyfi** [traefik/piceus#57]
_spinoff of issue from_ https://github.com/traefik/plugindemowasm/issues/6 

I wrote a Traefik WASM plugin using [Grain](https://grain-lang.org), originally just try both Grain and Traefik's WASM support.  Since it did... I decided to write it up into a demo project here:
https://github.com/tikoci/traefik-wasm-grain

But despite doing have a valid `.traefik.yml` including working `testData` per the "pluginwasmdemo" project, the Traefik Plugin Catalog never found the Grain-based WASM plugin.  And never got a failure GitHub issue either.  Eventually, I found this project which had the clue in `scrapper.go` with the GitHub query used:
 [searchQuery = "topic:traefik-plugin language:Go archived:false is:public"](https://github.com/traefik/piceus/blob/70984184131fbd6420628af44d1a0417c361d93c/pkg/core/scrapper.go#L43)

Once I learned how GitHub detects programming languages, and added `.gitattributes` to GitHub to say the code was Go...Traefik's Catalog found it, and apparently validated it.   

As noted in https://github.com/traefik/plugindemowasm/issues/6 , I'm not sure the right solution.  But overriding language detection for WASM plugins is not a great long-term solution.

**Comment by mloiseleur** [comment]
Thanks for your interest in Traefik and this detailed issue.

This example plugin using Grain is now browsed correctly by the bot and so, it appears in the catalog [here](https://plugins.traefik.io/plugins/666374dee8d831193077b35b/example-wasm-plugin-using-grain).

Feel free to re-open this issue or open a new one if we missed something.
