### ISSUE TITLE
Request to remove chaitin/traefik-t1k plugin

### ISSUE THREAD

**Issue by blaisewang** [traefik/piceus#64]
Hello,

We have recently made the repository for the chaitin/traefik-t1k plugin private. However, I noticed that the plugin is still listed in the plugin catalog and can still be installed.

We kindly request that this plugin be removed from the plugin catalog and made unavailable for installation.  Additionally, if possible, I believe it would be a great feature to automatically remove plugins from the catalog when their repositories become unavailable.

Thank you very much for your assistance.

**Comment by mloiseleur** [comment]
Hello,

I was not able to find it in the plugin catalog. Would you please provide a link to it ?

**Comment by ldez** [comment]
FYI, I don't know if it's important for you, but your plugin is inside Go Proxies, so your code is publicly available (it's not related to Piceus).
I don't know if it's possible to remove it from Go Proxies (I don't think so).

https://pkg.go.dev/github.com/chaitin/traefik-t1k

```bash
curl https://proxy.golang.org/github.com/chaitin/traefik-t1k/@v/v1.0.0.zip -o tik.zip
```

**Comment by mmatur** [comment]
Hi @blaisewang,

Your plugin has been removed from the Traefik plugin catalog.

Closing the issue accordingly
