### ISSUE TITLE
Not receiving scans from the Traefik plugin catalog in custom plugin

### ISSUE THREAD

**Issue by amj1985** [traefik/piceus#72]
I am not receiving more scans from the Traefik plugin catalog in the repository. I received the first one very quickly when it was ready and added the topic, but after closing the issue I have not received any more scans. Do you know what could be happening?

repository: https://github.com/amj1985/traefik-unleash-plugin
fixed and closed issue: https://github.com/amj1985/traefik-unleash-plugin/issues/11

**Comment by mloiseleur** [comment]
Hello @amj1985,

That's because the `New` func is blocking.

In order to avoid adding plugin which are not starting, piceus tries to call `New`, see [here](https://github.com/traefik/piceus/blob/master/pkg/core/yaegi.go#L169). I invite you to fix it and it should be indexed a few hours laters

**Comment by mloiseleur** [comment]
Thanks to this issue, we have improved _piceus_ to open an issue in this case (see #73).
So, I'm closing this one. 

Feel free to re-open it if we missed something.
