### ISSUE TITLE
Plugin not listed, seems to comply with requirements?

### ISSUE THREAD

**Issue by cdwiegand** [traefik/piceus#78]
I'm trying to figure out why my plugin, https://github.com/cdwiegand/traefik-add-trace-id-header  isn't showing up in the plugin registry. I've gone through the checklist and can't find any of them I'm not meeting?

- The traefik-plugin topic must be set on your repository. Check.
- There must be a .traefik.yml file at the root of your project describing your plugin, and it must have a valid testData property for testing purposes. Check (as far as I can tell, there's not a way I'm seeing for me to validate the testData is correct, but I assume it would open an issue if the test failed?)
- There must be a valid go.mod file at the root of your project. Check.
- Your plugin must be versioned with a git tag. Check. v0.2.2
- If you have package dependencies, they must be vendored and added to your GitHub repository. Check - there's only one, it's embedded and I even removed it from the go.mod in case that was causing it.

But I'm not getting any issue opened on the repo (which is publicly accessible), so any ideas? Am I missing something obvious? I've tried to compare my set up to both the code I forked it from, as well as another recent now-closed issue to see if I could find anything that stood out.

**Comment by ldez** [comment]
Hello,

it's because you are using a fork: forks are excluded from the system.

**Comment by cdwiegand** [comment]
Of course! I'd say it might make sense to document that, but it makes perfect sense to me now. I've closed it, and I will resolve the fork shortly.

**Comment by mloiseleur** [comment]
@cdwiegand Thanks for your suggestion :+1:. It has been added to troubleshooting section.
