### ISSUE TITLE
Request to remove plugin 

### ISSUE THREAD

**Issue by BrinkmannMi** [traefik/piceus#79]
Hello, 

since I recently changed my Github username, my plugin now appears twice in your catalog. 
Could you please delete the old version:

https://plugins.traefik.io/plugins/66c260e1e365a3d6705994ec/auth-with-exceptions

I apologize for the inconvenience. 

Thank you very much in advance!

**Comment by mloiseleur** [comment]
The plugin does not appear in the list anymore.
Feel free to re-open this issue if we missed something.
