### ISSUE TITLE
Help with plugin repo transfer

### ISSUE THREAD

**Issue by agilezebra** [traefik/piceus#82]
A while ago we created this plugin:
https://plugins.traefik.io/plugins/64e78597f55a32789ebfbd82/dynamic-jwt-validation-middleware 
which was originally publicly hosted from here:
https://github.com/Brainnwave/jwt-middleware

Unfortunately Brainnwave has now entered administration. To keep the plugin actively supported, I have transferred the repo back to my personal account: https://github.com/agilezebra/jwt-middleware where I will continue maintaining it as required. I also cloned the repo back to its original location in case anyone comes looking there.

My issues are:
1)	I can’t seem to get the traefik plugin catalog to pick up the repo at the new location, even though its topic is set (and I think everything else is correct). Is it possibly due to some metadata that means the plugin catalog knows it has already found this repo at a different location? Is there any way to manually correct this?
2)	It’s obviously very important that we don’t leave anyone high and dry that is already using the plugin from its original location. How best can we ensure anyone using it from there has continuity but with new development happening at the new location. I note that the previous releases are not present in the cloned back repo, even though the tags are, but everything seems to be working ok with any traefik configurations that are still using it from there. Does this seem expected?

Thanks in advance for your help.

**Comment by agilezebra** [comment]
Thanks for the help with the above issue (I'd missed the notification). 
Now that we have gotten the new repo included in the catalog, can the other one be safely removed from the catalog without affecting anyone referencing it from https://github.com/Brainnwave/jwt-middleware ?

**Comment by mloiseleur** [comment]
The https://github.com/Brainnwave/jwt-middleware  plugin has been removed from the catalog.

**Comment by mloiseleur** [comment]
@agilezebra sorry for that. It's not something we do very often. We added a specific rewrite for this plugin. Users with previous repository should (now) be able to still use it.

**Comment by agilezebra** [comment]
Thanks for the work around guys. Appreciate it.
