### ISSUE TITLE
Request to remove a plugin

### ISSUE THREAD

**Issue by yurasavin** [traefik/piceus#86]
Hi! Could you please remove the plugin above since I had to recreate it in a new repo
https://github.com/yurasavin/traefikchronoheader

**Comment by mloiseleur** [comment]
What is the precise URL of the new repo ?

**Comment by yurasavin** [comment]
https://github.com/yurasavin/traefiktimestampheader

**Comment by yurasavin** [comment]
The reason is this error 
```
unsupported plugin: the module name ([github.com/yurasavin/traefikChronoHeader](http://github.com/yurasavin/traefikChronoHeader)) doesn't contain the GitHub repository name ([github.com/yurasavin/traefikchronoheader](http://github.com/yurasavin/traefikchronoheader))
```

I renamed the initial repo several times because of lining errors...😁

**Comment by mloiseleur** [comment]
I don't find https://github.com/yurasavin/traefikchronoheader in the catalog, so I guess there is nothing to remove.
Did I miss something ?

**Comment by yurasavin** [comment]
Oh, I'm sorry for the confusing. As I said before I several times renamed the repo fighting with traefik bot and linter rules.

Here is the correct repo URL https://github.com/yurasavin/traefik-chrono-header
Here is the plugin page https://plugins.traefik.io/plugins/67491225573cd7803d65cb20/chrono-header

**Comment by mloiseleur** [comment]
I understand that there is no redirection needed, it seems safe to just delete it.

Would you please confirm my understanding ?

**Comment by yurasavin** [comment]
yes, that's correct

**Comment by mloiseleur** [comment]
The plugin has been removed.
