### ISSUE TITLE
Plugin Analyzer has detected a problem

### ISSUE THREAD

**Issue by RouxAntoine** [traefik/piceus#88]
I have issue in this plugin validation

https://github.com/RouxAntoine/reproxied/issues/5

this is a fork of another plugin.
Yaegi does not seems to appreciate the LogLevel attribute here https://github.com/RouxAntoine/reproxied/blob/ea26d856edeb0b11aed2c3d4e7c0a49954fccf7a/reproxied.go#L20 which is a type alias to int.

Do you have some clue please ?

**Comment by mloiseleur** [comment]
The error opened in the issue seems valid.
It's an int, so it [cannot be set](https://github.com/RouxAntoine/reproxied/blob/master/.traefik.yml#L12) as the string "INFO".

**Comment by RouxAntoine** [comment]
Hello thanks @mloiseleur I miss the .traefik.yml file all good I will try this
